/* Generated by PeachPy 0.2.0 from ../add.py */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif


uint64_t add(void* s_data, size_t s_len, size_t s_cap);


#ifdef __cplusplus
} /* extern "C" */
#endif
