// Generated by PeachPy 0.2.0 from add.py


// func add(f uintptr) uint64
TEXT ·add(SB),4,$0-16
	MOVQ f+0(FP), AX
	BYTE $0x48; BYTE $0x0F; BYTE $0xB7; BYTE $0x58; BYTE $0x02 // MOVZX rbx, word [rax + 2]
	ADDQ 8(AX), BX
	MOVQ BX, ret+8(FP)
	RET
